[constant]
cmd = "target/release/constant"
slash_args = ["--value"]
inputs = []
outputs = ["output"]

[phasor]
cmd = "target/release/phasor"
inputs = ["frequency"]
outputs = ["phase"]

[delay]
cmd = "target/release/delay"
slash_args = ["--max-delay"]
inputs = ["x", "delay"]
outputs = ["output"]

[noise]
cmd = "target/release/noise"
inputs = []
outputs = ["output"]

[n]
expansion = "noise"

[fn1]
cmd = "target/release/fn1"
slash_args = ["--fn"]
inputs = ["x"]
outputs = ["output"]

[fn2]
cmd = "target/release/fn2"
slash_args = ["--fn"]
inputs = ["x", "y"]
outputs = ["output"]

[fn3]
cmd = "target/release/fn3"
slash_args = ["--fn"]
inputs = ["x", "y", "z"]
outputs = ["output"]

[unit]
expansion = "fn1/unit"

[circle]
expansion = "fn1/circle"

[sin]
expansion = "fn1/sin"

[cos]
expansion = "fn1/cos"

[add]
expansion = "fn2/add"

["+"]
expansion = "add"

[sub]
expansion = "fn2/sub"

["-"]
expansion = "sub"

[mul]
expansion = "fn2/mul"

["*"]
expansion = "mul"

[div]
expansion = "fn2/div"

["%"]
expansion = "div"

[range]
expansion = "fn3/range"

[r]
expansion = "range"

# Oscillators

[sine]
expansion = "phasor fn1/sine"

[cosine]
expansion = "phasor fn1/cosine"

[tri]
expansion = "phasor fn1/triangle"

[saw]
expansion = "phasor"

[pulse]
expansion = "swap phasor swap fn2/rectangle"

[p]
expansion = "pulse"

[s]
expansion = "sine"

[t]
expansion = "tri"

[w]
expansion = "saw"
